In [2]:
#Create array

import numpy as np

arr = np.array(np.random.randint(1,101,size=100))

print(arr)

[ 36  58  20   3  29  81  59  98  64  58  83  50  94  43  27  48  22  57
  14  26  15  36  45  27  87  80  56  65  56  30  57  68  13  88  44  92
   3  34   3  38  44  59  36  38  65  97  62  67  62  19   2  71  86  51
  67  25  17  97  43  25  45  85  54  12  64  98  30  36  41  53  45  86
  50  24  25  14  57 100   6  18  36  57  40  38  42  54   9  14   2  47
  11   8   7  49   1  49  51  77   5  33]


In [3]:
# Calculate array stats

print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))

45.13
44.5
26.68732095958678


In [4]:
# Sort array and print top 5 values

arr.sort()
print(arr[0:5])

[1 2 2 3 3]


In [5]:
# Create 5 by 5 matrix

matrix = np.arange(25).reshape(5, 5)
print(matrix)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [16]:
# Fill diagonal with zeroes

np.fill_diagonal(matrix,0)
print(matrix)

[[ 0  1  2  3  4]
 [ 5  0  7  8  9]
 [10 11  0 13 14]
 [15 16 17  0 19]
 [20 21 22 23  0]]


In [17]:
# Multiply by transpose

mat_transpose = np.transpose(matrix)
product = matrix * mat_transpose
print(product)

[[  0   5  20  45  80]
 [  5   0  77 128 189]
 [ 20  77   0 221 308]
 [ 45 128 221   0 437]
 [ 80 189 308 437   0]]


In [13]:
# Generate 50 random values

array = np.random.randint(-5,5,size=50)
print(array)

[ 0  4 -3  4 -2  3  3  0 -2  1  0 -1  4 -2 -1 -5 -4 -4  0 -2  3  2 -2 -3
  0  3 -5 -3  3  1  2  4  3  1 -5 -4  4  4 -4 -1  2  2  1  3  4  0 -4  0
 -2 -1]


In [14]:
# Find count of positive and negative

positives = np.sum(array > 0)
negatives = np.sum(array < 0)
between = np.sum((array >= -1) & (array <= 1))

print("Counts:")
print("Positive:", positives)
print("Negative:", negatives)
print("Between -1 and 1:", between)

Counts:
Positive: 22
Negative: 21
Between -1 and 1: 15
